#!/bin/bash

rsync -avz --exclude '.dropbox'  \
        --delete \
        /home/jimmy/Dropbox/Website\ Pics/ \
         /home/www/ppw.schappet.com/htdocs/sites/default/files/images/ \
         > /dev/null 2>&1

